/*
* generated by Xtext
*/
package org.waml.w3c.webidl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WebIDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/waml/w3c/webidl/parser/antlr/internal/InternalWebIDL.tokens");
	}
}
