/*
* generated by Xtext
*/
package org.waml.w3c.webidl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.waml.w3c.webidl.services.WebIDLGrammarAccess;

public class WebIDLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private WebIDLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.waml.w3c.webidl.parser.antlr.internal.InternalWebIDLParser createParser(XtextTokenStream stream) {
		return new org.waml.w3c.webidl.parser.antlr.internal.InternalWebIDLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "IDLDefinitions";
	}
	
	public WebIDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WebIDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
