/*
 * generated by Xtext
 */
package org.waml.w3c.webidl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WebIDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.waml.w3c.webidl.ui.internal.WebIDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.waml.w3c.webidl.ui.internal.WebIDLActivator.getInstance().getInjector("org.waml.w3c.webidl.WebIDL");
	}
	
}
