/*
 * generated by Xtext
 */
package org.waml.w3c.webidl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WebIDLUiModule extends org.waml.w3c.webidl.ui.AbstractWebIDLUiModule {
	public WebIDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
