/*
* generated by Xtext
*/
package org.waml.w3c.webidl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class WebIDLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
