/*
* generated by Xtext
*/
package org.waml.w3c.webidl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class WebIDLTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
