/*
* generated by Xtext
*/
package org.waml.w3c.webidl.ui.contentassist;

import org.waml.w3c.webidl.ui.contentassist.AbstractWebIDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WebIDLProposalProvider extends AbstractWebIDLProposalProvider {

}
