/*
 * generated by Xtext
 */
package org.waml.w3c.webidl;

import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.waml.w3c.webidl.scoping.WebIDLQualifiedNameConverter;
import org.waml.w3c.webidl.scoping.WebIDLScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WebIDLRuntimeModule extends org.waml.w3c.webidl.AbstractWebIDLRuntimeModule {

	
	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter(){
		return WebIDLQualifiedNameConverter.class;
	}
	
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return WebIDLScopeProvider.class;
	}
}
